export const levelStyles = {
  EXPERT: {
    background: "bg-gradient-to-br from-red-50 via-rose-50 to-red-100",
    border: "border-red-800",
    borderSecondary: "border-red-600",
    badgeColor: "bg-red-700",
    textColor: "text-red-800",
    titleColor: "text-red-900",
    nameColor: "text-red-900",
    nameUnderline: "bg-red-900",
    metricsBackground: "bg-red-50",
    metricsBorder: "border-red-200",
    watermarkColor: "text-red-800",
    sealColor: "bg-red-100 border-red-800 text-red-800",
    cornerAccent: "border-red-800",
    ribbonGradient: "bg-gradient-to-r from-red-700 to-red-800",
  },
  ADVANCED: {
    background: "bg-gradient-to-br from-green-50 via-emerald-50 to-green-100",
    border: "border-green-800",
    borderSecondary: "border-green-600",
    badgeColor: "bg-green-700",
    textColor: "text-green-800",
    titleColor: "text-green-900",
    nameColor: "text-green-900",
    nameUnderline: "bg-green-900",
    metricsBackground: "bg-green-50",
    metricsBorder: "border-green-200",
    watermarkColor: "text-green-800",
    sealColor: "bg-green-100 border-green-800 text-green-800",
    cornerAccent: "border-green-800",
    ribbonGradient: "bg-gradient-to-r from-green-700 to-green-800",
  },
  INTERMEDIATE: {
    background: "bg-gradient-to-br from-blue-50 via-sky-50 to-blue-100",
    border: "border-blue-800",
    borderSecondary: "border-blue-600",
    badgeColor: "bg-blue-700",
    textColor: "text-blue-800",
    titleColor: "text-blue-900",
    nameColor: "text-blue-900",
    nameUnderline: "bg-blue-900",
    metricsBackground: "bg-blue-50",
    metricsBorder: "border-blue-200",
    watermarkColor: "text-blue-800",
    sealColor: "bg-blue-100 border-blue-800 text-blue-800",
    cornerAccent: "border-blue-800",
    ribbonGradient: "bg-gradient-to-r from-blue-700 to-blue-800",
  },
  BEGINNER: {
    background: "bg-gradient-to-br from-yellow-50 via-amber-50 to-yellow-100",
    border: "border-yellow-800",
    borderSecondary: "border-yellow-600",
    badgeColor: "bg-yellow-600",
    textColor: "text-yellow-800",
    titleColor: "text-yellow-900",
    nameColor: "text-yellow-900",
    nameUnderline: "bg-yellow-900",
    metricsBackground: "bg-yellow-50",
    metricsBorder: "border-yellow-200",
    watermarkColor: "text-yellow-800",
    sealColor: "bg-yellow-100 border-yellow-800 text-yellow-800",
    cornerAccent: "border-yellow-800",
    ribbonGradient: "bg-gradient-to-r from-yellow-600 to-yellow-700",
  },
};
